import {useEffect,useRef,useState} from 'react';
import {Bot,MessageCircle,RotateCcw,Send,Sparkles,X} from 'lucide-react';
import {api} from '../api';import {useAuth} from '../App';import '../assistant.css';

const welcome=name=>({role:'assistant',content:`Hi ${name.split(' ')[0]}! Ask me about current roles, games, Game Heads, terms, player sheets, or team victories.`});
const suggestions=['Who is the current Support Coordinator?','List games and their Game Heads','Who won the latest recorded match?'];

export default function ChatWidget(){const{user}=useAuth();const[open,setOpen]=useState(false);const[input,setInput]=useState('');const[busy,setBusy]=useState(false);const[messages,setMessages]=useState(()=>[welcome(user.name)]);const endRef=useRef(null);
  useEffect(()=>{if(open)endRef.current?.scrollIntoView({behavior:'smooth'})},[messages,busy,open]);
  const ask=async text=>{const question=String(text??input).trim();if(!question||busy)return;const history=messages.slice(-10);setMessages(items=>[...items,{role:'user',content:question}]);setInput('');setBusy(true);try{const result=await api.post('/assistant/chat',{message:question,history},{timeoutMs:32000});setMessages(items=>[...items,{role:'assistant',content:result.answer}])}catch(error){setMessages(items=>[...items,{role:'error',content:error.message}])}finally{setBusy(false)}};
  const keyDown=event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();ask()}};
  const reset=()=>{setMessages([welcome(user.name)]);setInput('')};
  return <div className={`ai-chat ${open?'open':''}`}>{open&&<section className="ai-chat-panel" aria-label="CUST Sports Week Assistant"><header><div className="ai-bot-mark"><Bot/></div><div><b>CUST Sports Assistant</b><span><i/> Live sports database</span></div><button onClick={reset} title="New conversation"><RotateCcw/></button><button onClick={()=>setOpen(false)} title="Close assistant"><X/></button></header><div className="ai-privacy"><Sparkles/><span>Sports information only · Sensitive account data is protected</span></div><div className="ai-messages">{messages.map((message,index)=><div className={`ai-message ${message.role}`} key={index}>{message.role==='assistant'&&<Bot/>}<p>{message.content}</p></div>)}{messages.length===1&&<div className="ai-suggestions">{suggestions.map(item=><button key={item} onClick={()=>ask(item)}>{item}</button>)}</div>}{busy&&<div className="ai-message assistant"><Bot/><div className="ai-typing"><i/><i/><i/></div></div>}<div ref={endRef}/></div><footer><textarea value={input} onChange={event=>setInput(event.target.value)} onKeyDown={keyDown} placeholder="Ask about Sports Week…" rows="1" maxLength="1200"/><button onClick={()=>ask()} disabled={!input.trim()||busy} aria-label="Send question"><Send/></button></footer></section>}<button className="ai-chat-launcher" onClick={()=>setOpen(!open)} aria-label={open?'Close AI assistant':'Open AI assistant'}>{open?<X/>:<><MessageCircle/><span><Sparkles/></span></>}</button></div>}
