import {useEffect,useState} from 'react';
import {NavLink,useLocation} from 'react-router-dom';
import {Archive,Award,Bell,ChevronDown,ClipboardList,Gamepad2,LayoutDashboard,LogOut,Menu,MessageSquareText,Megaphone,ShieldCheck,Trophy,Users,X} from 'lucide-react';
import {useAuth,useToast} from '../App';import {api} from '../api';
import ChatWidget from './ChatWidget';
import Modal,{Field} from './Modal';
const roleName=(user)=>user.displayRole||({SUPER_ADMIN:'Super Administrator',HOD:'Head of Department',TEACHER:'Faculty Member'}[user.baseRole]||user.baseRole);
export default function Layout({children}){const{user,logout}=useAuth();const flash=useToast();const[open,setOpen]=useState(false);const[profile,setProfile]=useState(false);const[count,setCount]=useState(0);const[reminderCount,setReminderCount]=useState(0);const[teamWins,setTeamWins]=useState({received:0,unseen:0});const[compose,setCompose]=useState(false);const[sending,setSending]=useState(false);const[sendError,setSendError]=useState('');const loc=useLocation();
 useEffect(()=>{const refresh=()=>{api.get('/notifications').then(x=>setCount(x.filter(n=>n.direction!=='SENT'&&!n.is_read).length)).catch(()=>{});if(user.baseRole!=='SUPER_ADMIN'){api.get('/reminders').then(x=>setReminderCount(x.reduce((total,item)=>total+(item.unread||0),0))).catch(()=>{});api.get('/badges/summary').then(setTeamWins).catch(()=>{})}};refresh();window.addEventListener('badges-updated',refresh);window.addEventListener('notifications-updated',refresh);const timer=setInterval(refresh,5000);return()=>{clearInterval(timer);window.removeEventListener('badges-updated',refresh);window.removeEventListener('notifications-updated',refresh)}},[loc.pathname,loc.search,user.baseRole]);
 const links=user.baseRole==='SUPER_ADMIN'
    ? [['/',LayoutDashboard,'Overview'],['/users',Users,'People'],['/reminders',MessageSquareText,'Reminders'],['/notifications',Bell,'Notifications']]
  : [['/',LayoutDashboard,'Overview'],...((user.baseRole==='HOD'||user.displayRole==='Support Coordinator')?[['/users',Users,'People']]:[]),['/games',Gamepad2,'Games'],['/sheets',ClipboardList,'Player Sheets'],...(user.displayRole==='Support Coordinator'?[['/terms',Archive,'Term Archive'],['/badges',Award,'Badge Studio']]:[]),...(teamWins.received>0?[['/team-wins',Trophy,'Team Win']]:[]),['/announcements',Megaphone,'Announcements'],['/reminders',MessageSquareText,'Reminders'],['/notifications',Bell,'Notifications']];
 const targets=user.baseRole==='SUPER_ADMIN'?[['HOD','Head of Department'],['SUPPORT_COORDINATOR','Sports Coordinator'],['TEACHERS','All Teachers']]:user.baseRole==='HOD'?[['SUPPORT_COORDINATOR','Sports Coordinator'],['TEACHERS','All Teachers']]:user.displayRole==='Support Coordinator'?[['HOD','Head of Department'],['TEACHERS','All Teachers'],['SUPER_ADMIN','Super Admin']]:[];
 const sendBroadcast=async event=>{event.preventDefault();setSendError('');const formElement=event.currentTarget;const form=new FormData(formElement);const audiences=form.getAll('audiences');if(!audiences.length){setSendError('Choose at least one recipient group.');return}setSending(true);try{const result=await api.post('/notifications/broadcast',{title:form.get('title'),message:form.get('message'),audiences});setCompose(false);formElement.reset();window.dispatchEvent(new Event('notifications-updated'));flash(result.message)}catch(error){setSendError(error.message)}finally{setSending(false)}};
 return <div className="shell"><aside className={open?'sidebar open':'sidebar'}><div className="brand"><img src="/cust-logo.jpg"/><div><b>CUST</b><span>Sports Week</span></div><button onClick={()=>setOpen(false)}><X/></button></div><nav><small>WORKSPACE</small>{links.map(([to,Icon,label])=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)}><Icon size={19}/><span>{label}</span>{label==='Team Win'&&teamWins.unseen>0&&<em>{teamWins.unseen}</em>}{label==='Reminders'&&reminderCount>0&&<em>{reminderCount}</em>}{label==='Notifications'&&count>0&&<em>{count}</em>}</NavLink>)}</nav><div className="sidebar-foot"><ShieldCheck size={18}/><div><b>Secure workspace</b><span>Role-based access active</span></div></div></aside><main><header className="topbar"><button className="menu-btn" onClick={()=>setOpen(true)}><Menu/></button><div className="top-title"><span>Capital University of Science & Technology</span><b>Sports Week Management</b></div><div className="top-actions"><NavLink to="/notifications" className="bell" aria-label="View notifications"><Bell size={20}/>{count>0&&<i>{count}</i>}</NavLink><button className="profile" onClick={()=>setProfile(!profile)}><span>{user.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><b>{user.name}</b><small>{roleName(user)}</small></div><ChevronDown size={16}/></button>{profile&&<div className="profile-menu"><div><b>{user.name}</b><span>{user.email}</span></div><button onClick={logout}><LogOut size={17}/> Sign out</button></div>}</div></header><div className="page">{children}</div></main>{open&&<div className="scrim" onClick={()=>setOpen(false)}/>}<ChatWidget/>{compose&&<Modal title="Send a notification" subtitle="Choose recipient groups. Each group will receive a separate notification." onClose={()=>!sending&&setCompose(false)}><form className="form-grid" onSubmit={sendBroadcast}><Field label="Title" wide><input name="title" maxLength="120" required placeholder="Notification title"/></Field><Field label="Message" wide><textarea name="message" rows="4" maxLength="1200" required placeholder="Write your message"/></Field><div className="broadcast-groups wide"><span>Send separately to</span>{targets.map(([value,label])=><label key={value}><input type="checkbox" name="audiences" value={value}/>{label}</label>)}</div>{sendError&&<p className="broadcast-error wide" role="alert">{sendError}</p>}<div className="form-actions wide"><button type="button" className="ghost" disabled={sending} onClick={()=>setCompose(false)}>Cancel</button><button className="primary" disabled={sending}>{sending?'Sending…':'Send notification'}</button></div></form></Modal>}</div>}
