import {useEffect,useRef,useState} from 'react';
import {Award,CheckCircle2,Download,FileText,LoaderCircle,Send,Share2,Sparkles,Trash2,Trophy,Users} from 'lucide-react';
import {api} from '../api';import {useToast} from '../App';import Modal,{Field} from '../components/Modal';import VictoryBadge from '../components/VictoryBadge';import {downloadBadge} from '../badgeDownload';import '../badges.css';

export default function BadgeStudio(){
  const flash=useToast();const generatedRef=useRef(null);const[badges,setBadges]=useState([]);const[games,setGames]=useState([]);const[recipients,setRecipients]=useState([]);const[generating,setGenerating]=useState(false);const[generated,setGenerated]=useState(null);const[shareBadge,setShareBadge]=useState(null);const[deleteBadge,setDeleteBadge]=useState(null);const[deleting,setDeleting]=useState(false);
  const load=()=>api.get('/badges').then(setBadges).catch(error=>flash(error.message,'error'));
  useEffect(()=>{load();Promise.all([api.get('/games'),api.get('/badges/recipients')]).then(([gameList,people])=>{setGames(gameList);setRecipients(people)}).catch(error=>flash(error.message,'error'))},[]);
  const generate=async event=>{event.preventDefault();const form=event.currentTarget;const data=Object.fromEntries(new FormData(form));setGenerating(true);setGenerated(null);try{await new Promise(resolve=>setTimeout(resolve,3000));const badge=await api.post('/badges',data);setGenerated(badge);form.reset();await load();flash('Victory badge generated')}catch(error){flash(error.message,'error')}finally{setGenerating(false)}};
  const share=async event=>{event.preventDefault();const form=new FormData(event.currentTarget);const audience=form.get('audience');const userIds=form.getAll('userIds').map(String);try{const result=await api.post(`/badges/${shareBadge.id}/share`,{audience,userIds});flash(result.message);setShareBadge(null);load()}catch(error){flash(error.message,'error')}};
  const remove=async()=>{setDeleting(true);try{const result=await api.delete(`/badges/${deleteBadge.id}`);flash(result.message);if(generated?.id===deleteBadge.id)setGenerated(null);setDeleteBadge(null);load()}catch(error){flash(error.message,'error')}finally{setDeleting(false)}};
  return <><div className="page-head badge-page-head"><div><p className="eyebrow">VICTORY RECOGNITION</p><h1>Badge Studio</h1><p>Create and share official team victory badges with HOD and registered Game Heads.</p></div><div className="badge-head-mark"><Award/><span>Official CUST recognition</span></div></div>
    <div className="badge-studio-grid"><section className="panel badge-builder"><header><div><h2>Create victory badge</h2><p>Enter the match result to generate a modern official badge.</p></div><Sparkles/></header><form className="form-grid" onSubmit={generate}><Field label="Batch number"><input name="batchNumber" placeholder="e.g. 261" required/></Field><Field label="Sport name"><select name="sportName" required><option value="">Select sport</option>{games.map(game=><option key={game.id} value={game.name}>{game.name}</option>)}</select></Field><Field label="Winning team"><input name="winningTeam" placeholder="e.g. Computing Warriors" required/></Field><Field label="Won against"><input name="opponentTeam" placeholder="e.g. Engineering Eagles" required/></Field><Field label="Score (optional)" wide><input name="score" placeholder="e.g. 3–1 or 178/6 vs 164/9"/></Field><Field label="Team Captain (optional)"><input name="teamCaptain" placeholder="Captain name"/></Field><Field label="Game Coordinator (optional)"><input name="gameCoordinator" placeholder="Coordinator name"/></Field><div className="form-actions wide"><button className="primary badge-generate" disabled={generating}>{generating?<><LoaderCircle className="spin"/> Generating…</>:<><Sparkles/> Generate badge</>}</button></div></form></section>
      <section className="panel badge-preview"><header><div><h2>Badge preview</h2><p>Your generated badge appears here.</p></div></header><div className="badge-preview-body">{generating?<div className="badge-generating"><div><Trophy/><i/><i/></div><h3>Your badge is generating</h3><p>Crafting the official victory design…</p></div>:generated?<><VictoryBadge ref={generatedRef} badge={generated}/><div className="generated-badge-actions"><button className="primary" onClick={()=>setShareBadge(generated)}><Share2/> Share badge</button><DownloadButtons badge={generated} badgeRef={generatedRef} flash={flash}/></div></>:<div className="badge-empty"><Award/><h3>Ready to celebrate a win</h3><p>Complete the match details and generate your first badge.</p></div>}</div></section></div>
    <section className="panel sent-badges"><header><div><h2>Created badges</h2><p>Review delivery and seen status for every victory badge.</p></div><span>{badges.length} total</span></header>{badges.length?<div className="sent-badge-grid">{badges.map(badge=><SentBadgeItem key={badge.id} badge={badge} flash={flash} share={()=>setShareBadge(badge)} remove={()=>setDeleteBadge(badge)}/>)}</div>:<div className="empty"><Award/><p>No badges created yet.</p></div>}</section>
    {shareBadge&&<ShareModal badge={shareBadge} recipients={recipients} share={share} close={()=>setShareBadge(null)}/>} {deleteBadge&&<Modal title="Permanently delete from teachers?" subtitle="This action cannot be undone." onClose={()=>!deleting&&setDeleteBadge(null)}><div className="badge-delete-confirm"><div><Trash2/></div><h3>{deleteBadge.winningTeam} · {deleteBadge.sportName}</h3><p>If you continue, this badge will be permanently removed from every teacher and HOD who received it. Their “Team Win” field will also disappear when no badges remain.</p><footer><button className="ghost" disabled={deleting} onClick={()=>setDeleteBadge(null)}>Cancel</button><button className="danger-confirm" disabled={deleting} onClick={remove}><Trash2/>{deleting?'Deleting…':'Delete from everyone'}</button></footer></div></Modal>}
  </>;
}

function DownloadButtons({badge,badgeRef,flash}){const[working,setWorking]=useState('');const run=async format=>{setWorking(format);try{await downloadBadge(badgeRef.current,badge,format);flash(`${format==='pdf'?'PDF':'Image'} downloaded`)}catch(error){flash(error.message,'error')}finally{setWorking('')}};return <div className="badge-download-actions"><button className="secondary" disabled={!!working} onClick={()=>run('png')}><Download/>{working==='png'?'Saving…':'Image'}</button><button className="secondary" disabled={!!working} onClick={()=>run('pdf')}><FileText/>{working==='pdf'?'Saving…':'PDF'}</button></div>}
function SentBadgeItem({badge,flash,share,remove}){const badgeRef=useRef(null);return <article className="sent-badge-item"><VictoryBadge ref={badgeRef} badge={badge} compact/><div className="sent-badge-meta"><div><span><Users/> {badge.recipientCount||0} recipients</span><span><CheckCircle2/> {badge.seenCount||0} seen</span></div>{badge.recipientNames&&<p>Sent to {badge.recipientNames}</p>}<DownloadButtons badge={badge} badgeRef={badgeRef} flash={flash}/><div><button className="secondary" onClick={share}><Send/> Share</button><button className="badge-delete" onClick={remove}><Trash2/> Delete</button></div></div></article>}

function ShareModal({badge,recipients,share,close}){const[audience,setAudience]=useState('ALL_GAME_HEADS');const[selected,setSelected]=useState([]);const heads=recipients.filter(person=>person.baseRole!=='HOD');const toggle=id=>setSelected(items=>items.includes(id)?items.filter(item=>item!==id):[...items,id]);return <Modal title="Share victory badge" subtitle={`${badge.winningTeam} · ${badge.sportName}`} onClose={close}><form className="badge-share-form" onSubmit={share}><Field label="Audience" wide><select name="audience" value={audience} onChange={event=>{setAudience(event.target.value);setSelected([])}}><option value="ALL_GAME_HEADS">All registered Game Heads</option><option value="HOD">HOD</option><option value="SELECTED">Selected Game Heads</option></select></Field>{audience==='SELECTED'&&<div className="badge-recipient-picker"><div><span>Select Game Heads</span><small>{selected.length} selected</small></div>{heads.length?<div className="badge-recipient-list">{heads.map(person=><label className={selected.includes(person.id)?'selected':''} key={person.id}><input type="checkbox" name="userIds" value={person.id} checked={selected.includes(person.id)} onChange={()=>toggle(person.id)}/><i>{person.name.split(' ').map(word=>word[0]).slice(0,2).join('')}</i><p><b>{person.name}</b><span>{person.games||'Game Head'}</span></p><CheckCircle2/></label>)}</div>:<p className="no-badge-recipients">No active Game Heads are registered.</p>}</div>}<div className="share-audience-note"><Users/><p><b>{audience==='ALL_GAME_HEADS'?'All active Game Heads':audience==='HOD'?'Head of Department':`${selected.length} selected Game Head${selected.length===1?'':'s'}`}</b><span>Recipients will receive a notification and an animated Team Win section.</span></p></div><div className="form-actions"><button type="button" className="ghost" onClick={close}>Cancel</button><button className="primary" disabled={audience==='SELECTED'&&!selected.length}><Send/> Share badge</button></div></form></Modal>}
