import {useEffect,useState} from 'react';
import {ArrowRight,Bell,CalendarDays,CheckCircle2,ClipboardList,Download,Gamepad2,Inbox,Send,ShieldCheck,Trash2,UserCog,UserRoundCheck,Users} from 'lucide-react';
import {Link,useNavigate} from 'react-router-dom';
import {api} from '../api';import {useAuth,useToast} from '../App';
import Modal from '../components/Modal';
import {useConfirm} from '../components/ConfirmationDialog';

const fmt=date=>new Date(date+'Z').toLocaleDateString('en-GB',{day:'numeric',month:'short'});
export default function Dashboard(){
  const {user}=useAuth();const flash=useToast();const confirm=useConfirm();const [data,setData]=useState(null);const [deleteTarget,setDeleteTarget]=useState(null);useEffect(()=>{api.get('/dashboard').then(setData)},[]);
  if(!data)return <div className="skeleton-page"/>;if(user.baseRole==='SUPER_ADMIN')return <AdminDashboard user={user} data={data}/>;
  const s=data.stats;const cards=[['Total teachers',s.teachers,'Available faculty',Users],['Active games',s.activeGames,`of ${s.games} listed`,Gamepad2],['Game Heads',s.coordinators,'Active assignments',UserRoundCheck],['Submitted sheets',s.sheets,`${s.pending} drafts pending`,ClipboardList]];
  const exportExcel=async sheet=>{try{await api.download(`/sheets/${sheet.id}/export`,`${sheet.title}.xlsx`)}catch(error){flash(error.message,'error')}};
  const removeSheet=async scope=>{const everyone=scope==='everyone';if(!await confirm({title:everyone?'Delete this sheet for everyone?':'Delete this sheet for you?',message:everyone?'This permanently removes the sheet and its player records for all users.':'This removes the sheet from your account only.',confirmLabel:everyone?'Delete for everyone':'Delete for me'}))return;try{await api.delete(`/sheets/${deleteTarget.id}?scope=${scope}`);flash(everyone?'Sheet deleted for everyone':'Sheet deleted for you');setDeleteTarget(null);setData(await api.get('/dashboard'))}catch(error){flash(error.message,'error')}};
  const sent=data.recentSheets.filter(sheet=>sheet.direction==='SENT');const received=data.recentSheets.filter(sheet=>sheet.direction==='RECEIVED');
  return <><Welcome user={user}/>{user.baseRole==='TEACHER'&&<div className="assignment-banner"><div className="assignment-icon"><ShieldCheck/></div><div><span>YOUR CURRENT ASSIGNMENT</span><h3>{data.assignments.length?data.assignments.map(assignment=>assignment.game?`${assignment.game} Game Head`:'Support Coordinator').join(' · '):'Currently not assigned any role'}</h3><p>{data.assignments.length?`Assigned by ${data.assignments[0].assignedBy}`:'Your dashboard will update automatically when an assignment is made.'}</p></div></div>}<Stats cards={cards}/><div className="dashboard-grid"><section className="panel wide-panel"><header><div><h2>Recent player sheets</h2><p>Separated by sheets you sent and received</p></div><Link to="/sheets">View all <ArrowRight size={16}/></Link></header><div className="sheet-directions"><SheetColumn title="Sent" icon={Send} sheets={sent} empty="No sent sheets." onExport={exportExcel} onDelete={setDeleteTarget}/><SheetColumn title="Received" icon={Inbox} sheets={received} empty="No received sheets." onExport={exportExcel} onDelete={setDeleteTarget}/></div></section><NotificationPanel data={data}/></div>{deleteTarget&&<DeleteSheetModal sheet={deleteTarget} canEveryone={deleteTarget.submittedById===user.id||user.baseRole==='HOD'||user.displayRole==='Support Coordinator'} remove={removeSheet} close={()=>setDeleteTarget(null)}/>}</>;
}
function SheetColumn({title,icon:Icon,sheets,empty,onExport,onDelete}){return <div className="sheet-direction"><h3><Icon/>{title}<em>{sheets.length}</em></h3>{sheets.length?sheets.map(sheet=><div className="mini-sheet" key={sheet.id}><Link to={`/sheets/${sheet.id}`}><span className="sheet-game">{sheet.game.slice(0,2).toUpperCase()}</span><p><b>{sheet.title}</b><small>{sheet.game} · {sheet.submittedBy}</small></p><time>{fmt(sheet.createdAt)}</time></Link><button onClick={()=>onExport(sheet)} title="Export Excel"><Download/></button><button className="mini-delete" onClick={()=>onDelete(sheet)} title="Delete sheet"><Trash2/></button></div>):<div className="direction-empty">{empty}</div>}</div>}
function DeleteSheetModal({sheet,canEveryone,remove,close}){return <Modal title="Delete player sheet" subtitle={sheet.title} onClose={close}><div className="delete-sheet-options"><button onClick={()=>remove('me')}><div><b>Delete for me</b><span>Only remove it from your account.</span></div></button>{canEveryone&&<button className="danger-option" onClick={()=>remove('everyone')}><div><b>Delete for everyone</b><span>Permanently remove it for all users.</span></div></button>}</div></Modal>}
function AdminDashboard({user,data}){const s=data.stats;const cards=[['Total accounts',s.activeUsers+s.inactiveUsers,'All system users',Users],['Active accounts',s.activeUsers,'Can currently sign in',UserRoundCheck],['HOD accounts',s.hods,'Administrative users',ShieldCheck],['Inactive accounts',s.inactiveUsers,'Access suspended',UserCog]];return <><div className="welcome"><div><p className="eyebrow">ACCOUNT ADMINISTRATION</p><h1>Good {new Date().getHours()<12?'morning':new Date().getHours()<17?'afternoon':'evening'}, {user.name.split(' ')[0]}.</h1><p>Create and maintain the credentials used by HODs and teachers.</p></div><div className="event-pill"><ShieldCheck/><div><span>SECURE ACCESS</span><b>Account management</b></div></div></div><Stats cards={cards}/><div className="dashboard-grid"><section className="panel admin-account-panel"><div className="admin-account-icon"><UserCog/></div><div><p className="eyebrow">MAIN RESPONSIBILITY</p><h2>Manage institutional login accounts</h2><p>Create HOD and teacher accounts, update their details, reset passwords, and activate or deactivate system access.</p><Link className="primary" to="/users">Open account management <ArrowRight size={16}/></Link></div></section><NotificationPanel data={data}/></div></>}
function Welcome({user}){return <div className="welcome"><div><p className="eyebrow">{new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}</p><h1>Good {new Date().getHours()<12?'morning':new Date().getHours()<17?'afternoon':'evening'}, {user.name.split(' ')[0]}.</h1><p>Here’s what’s happening across Sports Week today.</p></div><div className="event-pill"><CalendarDays/><div><span>SPORTS WEEK 2026</span><b>Operations dashboard</b></div></div></div>}
function Stats({cards}){return <div className="stat-grid">{cards.map(([label,value,note,Icon],index)=><article className="stat" key={label}><div className={`stat-icon c${index}`}><Icon/></div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></article>)}</div>}
function NotificationPanel({data}){const navigate=useNavigate();const open=async notification=>{if(!notification.is_read)await api.patch(`/notifications/${notification.id}/read`,{});navigate(notification.target_url||'/notifications')};return <section className="panel notification-panel"><header><div><h2>Notifications</h2><p>Recent updates</p></div><Link to="/notifications">View all</Link></header>{data.notifications.length?<div className="notification-list">{data.notifications.slice(0,4).map(notification=><button className="dashboard-notice" key={notification.id} onClick={()=>open(notification)}><span className={`notice-icon ${notification.type.toLowerCase()}`}><Bell/></span><p><b>{notification.title}</b><span>{notification.message}</span><time>{fmt(notification.created_at)}</time></p></button>)}</div>:<Empty text="You’re all caught up."/>}</section>}
function Empty({text}){return <div className="empty"><CheckCircle2/><p>{text}</p></div>}
