import {useEffect,useState} from 'react';
import {Bell,CheckCheck,ClipboardCheck,Forward,Send,Trash2,UserRoundCheck} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import {api} from '../api';import {useToast} from '../App';
import {useConfirm} from '../components/ConfirmationDialog';

export default function Notifications(){
  const [list,setList]=useState([]);const flash=useToast();const confirm=useConfirm();const navigate=useNavigate();
  const load=()=>api.get('/notifications').then(setList);useEffect(()=>{load()},[]);
  const open=async notification=>{if(notification.direction!=='SENT'&&!notification.is_read)await api.patch(`/notifications/${notification.id}/read`,{});navigate(notification.target_url||'/notifications')};
  const remove=async(notification,event)=>{event.stopPropagation();if(!await confirm({title:'Delete this notification?',message:'This notification will be removed from your activity centre.',confirmLabel:'Delete notification'}))return;try{await api.delete(notification.direction==='SENT'?`/notifications/sent/${notification.id}`:`/notifications/${notification.id}`);flash('Notification deleted');load()}catch(error){flash(error.message,'error')}};
  const readAll=async()=>{await api.patch('/notifications/read-all',{});flash('All notifications marked as read');load()};
  const icon=type=>type==='ASSIGNMENT'?UserRoundCheck:type==='SUBMISSION'?ClipboardCheck:type==='FORWARD'?Forward:Bell;
  return <><div className="page-head"><div><p className="eyebrow">ACTIVITY CENTRE</p><h1>Notifications</h1><p>Assignments, submissions, forwards, and delivery status.</p></div><button className="secondary" onClick={readAll}><CheckCheck/> Mark all as read</button></div><section className="panel notices-page">{list.map(notification=>{const Icon=notification.direction==='SENT'?Send:icon(notification.type);const sent=notification.direction==='SENT';const seen=sent&&notification.seen_count===notification.recipient_count;return <button key={`${notification.direction}-${notification.id}`} className={!sent&&!notification.is_read?'notice-row unread':'notice-row'} onClick={()=>open(notification)}><span className={`notice-icon ${sent?'sent':notification.type.toLowerCase()}`}><Icon/></span><div><b>{sent?sentTitle(notification):notification.title}</b><p>{sent?sentDescription(notification):notification.message}</p><time>{sent?`Sent to ${notification.recipient_names||notification.recipient_count+' recipient(s)'}`:notification.sender_name?`From ${notification.sender_name}`:''} · {new Date(notification.created_at+'Z').toLocaleString()}</time></div>{sent?<span className={seen?'delivery-status seen':'delivery-status'} title={seen?'Seen':'Unseen'}><CheckCheck/><small>{seen?'Seen':'Unseen'}</small></span>:!notification.is_read&&<i/>}<span className="delete-notice" onClick={event=>remove(notification,event)} title="Delete notification"><Trash2/></span></button>})}{!list.length&&<div className="empty"><Bell/><p>You’re all caught up.</p></div>}</section></>;
}
function sentTitle(notification){return notification.type==='FORWARD'?'Player sheet sent':notification.type==='SUBMISSION'?'Player sheet submitted':notification.type==='ASSIGNMENT'?'Assignment sent':'Update sent'}
function sentDescription(notification){const recipients=notification.recipient_names||`${notification.recipient_count} recipient(s)`;if(notification.type==='FORWARD')return `You sent a player sheet to ${recipients}.`;if(notification.type==='SUBMISSION')return `You submitted a player sheet to ${recipients}.`;if(notification.type==='ASSIGNMENT')return `You assigned a role to ${recipients}.`;return `You sent this update to ${recipients}.`}
