import {useEffect,useMemo,useRef,useState} from 'react';
import {CheckCheck,FileAudio,FileText,MessageSquareText,Paperclip,Send,Trash2} from 'lucide-react';
import {useSearchParams} from 'react-router-dom';
import {api} from '../api';
import {useAuth,useToast} from '../App';
import {useConfirm} from '../components/ConfirmationDialog';

export default function Reminders(){
  const {user}=useAuth();const flash=useToast();const confirm=useConfirm();const [params,setParams]=useSearchParams();
  const [conversations,setConversations]=useState([]);const [recipients,setRecipients]=useState([]);const [messages,setMessages]=useState([]);const [message,setMessage]=useState('');const [file,setFile]=useState(null);const [sending,setSending]=useState(false);const fileRef=useRef();
  const selectedId=params.get('user')||null;const canSend=user.baseRole==='HOD'||user.displayRole==='Support Coordinator'||user.baseRole==='TEACHER'||user.baseRole==='SUPER_ADMIN';
  const selected=useMemo(()=>{const conversation=conversations.find(item=>item.userId===selectedId);const recipient=recipients.find(item=>item.id===selectedId);return conversation&&recipient?{...conversation,...recipient}:conversation||recipient},[conversations,recipients,selectedId]);
  const loadConversations=()=>api.get('/reminders').then(setConversations);
  const loadThread=async id=>{if(!id){setMessages([]);return}const thread=await api.get(`/reminders/${id}`);setMessages(thread);await api.patch(`/reminders/${id}/seen`,{});loadConversations()};
  useEffect(()=>{loadConversations();if(canSend)api.get('/reminders/recipients').then(setRecipients)},[]);
  useEffect(()=>{loadThread(selectedId)},[selectedId]);
  useEffect(()=>{const timer=setInterval(()=>{loadConversations();if(selectedId)api.get(`/reminders/${selectedId}`).then(setMessages)},5000);return()=>clearInterval(timer)},[selectedId]);
  const choose=id=>setParams({user:String(id)});
  const send=async event=>{event.preventDefault();if(!selectedId)return flash('Select a recipient first','error');const body=new FormData();body.append('recipientId',selectedId);body.append('message',message);if(file)body.append('attachment',file);setSending(true);try{await api.post('/reminders',body);setMessage('');setFile(null);if(fileRef.current)fileRef.current.value='';flash('Message sent');await loadThread(selectedId);loadConversations()}catch(error){flash(error.message,'error')}finally{setSending(false)}};
  const removeMessage=async id=>{if(!await confirm({title:'Delete this message?',message:'This message and its attachment will be deleted.',confirmLabel:'Delete message'}))return;try{await api.delete(`/reminders/message/${id}`);flash('Message deleted');await loadThread(selectedId);loadConversations()}catch(error){flash(error.message,'error')}};
  return <><div className="page-head"><div><p className="eyebrow">COMMUNICATION</p><h1>Reminders</h1><p>Send operational messages and files with delivery receipts.</p></div>{canSend&&<select className="recipient-select" value={selectedId||''} onChange={event=>choose(event.target.value)}><option value="">New message…</option>{recipients.map(recipient=><option key={recipient.id} value={recipient.id}>{recipient.name} — {recipientLabel(recipient)}</option>)}</select>}</div><section className="reminder-shell"><aside className="conversation-list"><header><MessageSquareText/><div><b>Conversations</b><span>{conversations.length} active</span></div></header>{conversations.map(item=><button className={item.userId===selectedId?'conversation active':'conversation'} key={item.userId} onClick={()=>choose(item.userId)}><i>{item.name.split(' ').map(word=>word[0]).slice(0,2).join('')}</i><div><b>{item.name}</b><span>{item.lastMessage}</span></div>{item.unread>0&&<em>{item.unread}</em>}</button>)}{!conversations.length&&<div className="conversation-empty">No messages yet.</div>}</aside><div className="message-panel">{selected?<><header><i>{selected.name.split(' ').map(word=>word[0]).slice(0,2).join('')}</i><div><b>{selected.name}</b><span>{recipientLabel(selected)}</span></div></header><div className="message-stream">{messages.map(item=><Message key={item.id} item={item} mine={item.senderId===user.id} remove={removeMessage}/>)}</div>{canSend&&<form className="message-composer" onSubmit={send}><textarea value={message} onChange={event=>setMessage(event.target.value)} placeholder="Write a message or attach a file…" rows="2"/><div><label className="attach-button" title="Attach a file"><Paperclip/><input ref={fileRef} type="file" onChange={event=>setFile(event.target.files[0]||null)}/></label>{file&&<span className="file-chip">{file.name}</span>}<button className="primary" disabled={sending}><Send/>{sending?'Sending…':'Send'}</button></div></form>}</>:<div className="message-placeholder"><MessageSquareText/><h2>Select a conversation</h2><p>{canSend?'Choose a recipient to start a message.':'Open a message to view its contents.'}</p></div>}</div></section></>;
}
function recipientLabel(recipient){if(recipient.baseRole==='SUPER_ADMIN')return 'Super Admin';if(recipient.baseRole==='HOD')return 'Head of Department';if(recipient.assignments)return recipient.assignments.replaceAll(',', ' · ');return recipient.baseRole==='TEACHER'?'Teacher':'Registered User'}
function Message({item,mine,remove}){return <article className={mine?'message-bubble mine':'message-bubble'}><div>{item.message&&<p>{item.message}</p>}{item.attachmentUrl&&<Attachment item={item}/>}<button className="delete-message" onClick={()=>remove(item.id)} title="Delete message"><Trash2/></button></div><footer><time>{new Date(item.createdAt+'Z').toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}</time>{mine&&<span className={item.isSeen?'receipt seen':'receipt'}><CheckCheck/>{item.isSeen?'Seen':'Unseen'}</span>}</footer></article>}
function Attachment({item}){if(item.attachmentType?.startsWith('image/'))return <a href={item.attachmentUrl} target="_blank" rel="noreferrer"><img className="reminder-image" src={item.attachmentUrl} alt={item.attachmentName||'Reminder attachment'}/></a>;if(item.attachmentType?.startsWith('audio/'))return <div className="media-attachment"><FileAudio/><audio controls src={item.attachmentUrl}/></div>;if(item.attachmentType?.startsWith('video/'))return <video className="reminder-video" controls src={item.attachmentUrl}/>;return <a className="file-download" href={item.attachmentUrl} download={item.attachmentName||true}><FileText/><span>{item.attachmentName||'Download attachment'}</span></a>}
