import {useEffect,useRef,useState} from 'react';
import {Award,Download,Eye,FileText,Sparkles,Trash2,Trophy} from 'lucide-react';
import {useSearchParams} from 'react-router-dom';
import {api} from '../api';import {useToast} from '../App';import Modal from '../components/Modal';import VictoryBadge from '../components/VictoryBadge';import {downloadBadge} from '../badgeDownload';import '../badges.css';

export default function TeamWins(){const flash=useToast();const badgeRef=useRef(null);const[params]=useSearchParams();const[badges,setBadges]=useState([]);const[selected,setSelected]=useState(null);const[removeTarget,setRemoveTarget]=useState(null);const[downloading,setDownloading]=useState('');
  const load=async()=>{try{const list=await api.get('/badges');setBadges(list);const requested=params.get('badge');if(requested){const badge=list.find(item=>item.id===requested);if(badge)openBadge(badge)}}catch(error){flash(error.message,'error')}};
  useEffect(()=>{load()},[]);
  const openBadge=async badge=>{setSelected({...badge,isSeen:1});setBadges(items=>items.map(item=>item.id===badge.id?{...item,isSeen:1}:item));if(!badge.isSeen)api.patch(`/badges/${badge.id}/seen`,{}).catch(()=>{})};
  const remove=async()=>{try{const result=await api.delete(`/badges/${removeTarget.id}`);flash(result.message);setRemoveTarget(null);setSelected(null);await load();window.dispatchEvent(new Event('badges-updated'))}catch(error){flash(error.message,'error')}};
  const download=async format=>{setDownloading(format);try{await downloadBadge(badgeRef.current,selected,format);flash(`${format==='pdf'?'PDF':'Image'} downloaded`)}catch(error){flash(error.message,'error')}finally{setDownloading('')}};
  return <><section className="team-win-hero"><div className="confetti c1">✦</div><div className="confetti c2">●</div><div className="confetti c3">◆</div><div className="team-win-trophy"><Trophy/></div><div><p className="eyebrow">VICTORY GALLERY</p><h1>Team Win</h1><p>Celebrate the teams that made CUST Sports Week unforgettable.</p></div><Sparkles/></section>{badges.length?<div className="received-badge-grid">{badges.map(badge=><button className={`received-badge ${badge.isSeen?'':'unseen'}`} key={badge.id} onClick={()=>openBadge(badge)}><VictoryBadge badge={badge} compact/><footer><span>{badge.isSeen?<><Eye/> Viewed</>:<><Sparkles/> New victory</>}</span><small>Shared by {badge.createdBy}</small></footer></button>)}</div>:<div className="panel team-win-empty"><Award/><h2>No victory badges</h2><p>Your shared team achievements will appear here.</p></div>}
    {selected&&<Modal title="Official Team Victory" subtitle={`Shared by ${selected.createdBy}`} onClose={()=>setSelected(null)} size="large"><div className="received-badge-modal"><VictoryBadge ref={badgeRef} badge={selected}/><div className="received-badge-actions"><button className="secondary" disabled={!!downloading} onClick={()=>download('png')}><Download/>{downloading==='png'?'Saving…':'Download image'}</button><button className="secondary" disabled={!!downloading} onClick={()=>download('pdf')}><FileText/>{downloading==='pdf'?'Saving…':'Download PDF'}</button><button className="badge-delete" onClick={()=>{setRemoveTarget(selected);setSelected(null)}}><Trash2/> Remove</button></div></div></Modal>}{removeTarget&&<Modal title="Remove this badge?" subtitle="This only removes the badge from your account." onClose={()=>setRemoveTarget(null)}><div className="badge-delete-confirm"><div><Trash2/></div><h3>{removeTarget.winningTeam}</h3><p>You can remove this received badge if you no longer want it in your Team Win gallery.</p><footer><button className="ghost" onClick={()=>setRemoveTarget(null)}>Cancel</button><button className="danger-confirm" onClick={remove}><Trash2/> Remove badge</button></footer></div></Modal>}
  </>}
