import {useEffect,useMemo,useState} from 'react';
import {Archive,Download,FileSpreadsheet,Forward,Gamepad2,GraduationCap,Plus,UploadCloud,Users} from 'lucide-react';
import {useNavigate,useParams} from 'react-router-dom';
import {api} from '../api';import {useAuth,useToast} from '../App';import Modal,{Field} from '../components/Modal';

export default function Terms(){
  const {id}=useParams();const navigate=useNavigate();const {user}=useAuth();const flash=useToast();const canManage=user.displayRole==='Support Coordinator';
  const [terms,setTerms]=useState([]);const [detail,setDetail]=useState(null);const [tab,setTab]=useState('students');const [selectedGame,setSelectedGame]=useState('');const [modal,setModal]=useState(null);const [recipients,setRecipients]=useState([]);
  const loadTerms=()=>api.get('/terms').then(items=>{setTerms(items);if(!id&&items.length)navigate(`/terms/${items[0].id}`,{replace:true})});
  const loadDetail=()=>id?api.get(`/terms/${id}`).then(setDetail).catch(error=>flash(error.message,'error')):setDetail(null);
  useEffect(()=>{loadTerms();if(canManage)api.get('/terms/recipients').then(setRecipients)},[]);
  useEffect(()=>{setSelectedGame('');setTab('students');loadDetail()},[id]);
  const games=useMemo(()=>detail?[...new Set([...(detail.games||[]).map(game=>game.name),...detail.students.map(student=>student.gameName||'Unspecified')])].sort((a,b)=>a.localeCompare(b)):[],[detail]);
  const filteredStudents=useMemo(()=>detail&&selectedGame?detail.students.filter(student=>(student.gameName||'Unspecified')===selectedGame):[],[detail,selectedGame]);
  const create=async event=>{event.preventDefault();try{const data=Object.fromEntries(new FormData(event.currentTarget));const result=await api.post('/terms',data);flash(result.message);setModal(null);await loadTerms();navigate(`/terms/${result.id}`)}catch(error){flash(error.message,'error')}};
  const importExcel=async event=>{const file=event.target.files[0];if(!file||!id)return;const form=new FormData();form.append('file',file);try{const result=await api.post(`/terms/${id}/import`,form);flash(`${result.message}. Records are saved in the database and included in future exports.`);await loadDetail();loadTerms()}catch(error){flash(error.message,'error')}finally{event.target.value=''}};
  const exportExcel=async(type='complete',game='')=>{try{const query=new URLSearchParams();if(type!=='complete')query.set('type',type);if(game)query.set('game',game);const suffix=type==='teachers'?'Teachers':type==='students'?`${game}-Students`:'Archive';await api.download(`/terms/${id}/export${query.size?`?${query}`:''}`,`CUST-Term-${detail.term.code}-${suffix.replace(/[^a-z0-9]+/gi,'-')}.xlsx`)}catch(error){flash(error.message,'error')}};
  const downloadSelection=()=>tab==='teachers'?exportExcel('teachers'):selectedGame?exportExcel('students',selectedGame):flash('Select a game before downloading student records','error');
  const forward=async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));try{const result=await api.post(`/terms/${id}/forward`,{userId:data.userId,message:data.message});flash(result.message);setModal(null)}catch(error){flash(error.message,'error')}};
  return <>
    <div className="page-head term-page-head"><div><p className="eyebrow">HISTORICAL RECORDS</p><h1>Term archive</h1><p>Review batch-wise teacher responsibilities and historical student/player records.</p></div><div className="term-head-actions"><select value={id||''} onChange={event=>navigate(`/terms/${event.target.value}`)}><option value="">Select term</option>{terms.map(term=><option key={term.id} value={term.id}>{term.code} — {term.name}</option>)}</select>{canManage&&<button className="primary" onClick={()=>setModal({type:'create'})}><Plus/> Create term</button>}</div></div>
    {detail?<>
      <section className="term-hero"><div className="term-code">{detail.term.code}</div><div><span>{detail.term.status}</span><h2>{detail.term.name}</h2><p>Independent historical snapshot · Created {new Date(detail.term.createdAt+'Z').toLocaleDateString()}</p></div><div className="term-actions"><button className="secondary" onClick={downloadSelection} disabled={tab==='students'&&!selectedGame}><Download/> {tab==='teachers'?'Download teachers Excel':selectedGame?`Download ${selectedGame} Excel`:'Select game to download'}</button>{canManage&&<><label className="secondary term-upload"><UploadCloud/> Import students<input type="file" accept=".xlsx,.xls,.csv" onChange={importExcel}/></label><button className="primary" onClick={()=>setModal({type:'forward'})}><Forward/> Forward archive</button></>}</div></section>
      <div className="term-stats"><article><Users/><span><b>{detail.teachers.length}</b>Teacher records</span></article><article><GraduationCap/><span><b>{detail.students.length}</b>Student records</span></article><article><Archive/><span><b>{detail.term.code}</b>Batch code</span></article></div>
      <section className="panel term-records"><div className="term-tabs"><button className={tab==='students'?'active':''} onClick={()=>setTab('students')}><GraduationCap/> Students <em>{detail.students.length}</em></button><button className={tab==='teachers'?'active':''} onClick={()=>setTab('teachers')}><Users/> Teachers <em>{detail.teachers.length}</em></button></div>{tab==='students'?<StudentArchive games={games} selectedGame={selectedGame} selectGame={setSelectedGame} rows={filteredStudents}/>:<TeacherTable rows={detail.teachers}/>}</section>
    </>:<div className="empty term-empty"><Archive/><p>No term archive is available.</p></div>}
    {modal?.type==='create'&&<CreateTerm create={create} close={()=>setModal(null)}/>} 
    {modal?.type==='forward'&&<ForwardTerm term={detail.term} recipients={recipients} forward={forward} close={()=>setModal(null)}/>} 
  </>;
}

function StudentArchive({games,selectedGame,selectGame,rows}){return <><div className="game-strip-wrap"><div className="game-strip-label"><Gamepad2/><span>Select game</span></div><div className="term-game-strip">{games.map(game=><button className={selectedGame===game?'active':''} key={game} onClick={()=>selectGame(game)}>{game}</button>)}</div></div>{selectedGame?<><div className="selected-game-summary"><span>Showing</span><b>{selectedGame}</b><em>{rows.length} student{rows.length!==1?'s':''}</em></div><StudentTable rows={rows}/></>:<div className="game-select-empty"><Gamepad2/><h3>Select a game to view students</h3><p>Select a game, then use the download button above to export only that game's students.</p></div>}</>}
function StudentTable({rows}){return <div className="table-wrap"><table className="archive-table"><thead><tr><th>Student</th><th>Registration No.</th><th>Department</th><th>Semester</th><th>Section</th><th>Contact</th><th>Game</th><th>Position</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><b>{row.studentName}</b></td><td>{row.registrationNo}</td><td>{row.department}</td><td>{row.semester}</td><td>{row.section}</td><td>{row.contactNo}</td><td><span className="archive-game">{row.gameName||'Unspecified'}</span></td><td>{row.position||'—'}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty"><FileSpreadsheet/><p>No students are stored for this game.</p></div>}</div>}
function TeacherTable({rows}){return <div className="table-wrap"><table className="archive-table"><thead><tr><th>Teacher</th><th>Department</th><th>Base Role</th><th>Assigned Role</th><th>Game Responsibility</th><th>Remarks</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><div className="archive-teacher"><i>{row.teacherName.split(' ').map(word=>word[0]).slice(0,2).join('')}</i><span><b>{row.teacherName}</b><small>{row.email}</small></span></div></td><td>{row.department}</td><td>{row.baseRole}</td><td><span className="archive-role">{row.assignedRole||'Teacher'}</span></td><td><span className="archive-game">{row.gameName||'—'}</span></td><td>{row.remarks||'—'}</td></tr>)}</tbody></table></div>}
function CreateTerm({create,close}){return <Modal title="Create historical term" subtitle="Current teacher roles will be captured automatically." onClose={close}><form className="form-grid" onSubmit={create}><Field label="Batch / term code" wide><input name="code" placeholder="e.g. 221" required/></Field><Field label="Term name" wide><input name="name" placeholder="e.g. Spring 2022" required/></Field><div className="form-actions wide"><button type="button" className="ghost" onClick={close}>Cancel</button><button className="primary">Create term</button></div></form></Modal>}
function ForwardTerm({term,recipients,forward,close}){return <Modal title="Forward term archive" subtitle={`Share batch ${term.code} records with HOD or a teacher.`} onClose={close}><form className="form-grid" onSubmit={forward}><Field label="Recipient" wide><select name="userId" required><option value="">Select recipient</option>{recipients.map(recipient=><option key={recipient.id} value={recipient.id}>{recipient.name} · {recipient.baseRole==='HOD'?'HOD':'Teacher'}</option>)}</select></Field><Field label="Message" wide><textarea name="message" rows="3" placeholder="Add context for the recipient"/></Field><div className="form-actions wide"><button type="button" className="ghost" onClick={close}>Cancel</button><button className="primary">Forward archive</button></div></form></Modal>}
