import React from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import App from './App';
import './styles.css';
import './admin.css';
import './reminders.css';
import './clarity.css';
import './people.css';
import './terms.css';
import './responsive.css';
import './confirmation.css';
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
